package com.campaign.mvc.entity;


import javax.persistence.*;
import java.sql.Time;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MerchantBranchDealsDo generated by Vivek
 */

@Entity
@Table(name = "merchant_branch_deals")
public class MerchantBranchDealsDo implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "merchant_deals_pkey")
    private long merchantDealsPkey;

    @Column(name = "short_description")
    private String shortDescription;

    @Column(name = "target_sex")
    private String targetSex;

    @Column(name = "has_fixed_coupon_code")
    private Boolean hasFixedCouponCode;

    @Column(name = "no_of_deals")
    private long noOfDeals;

    @Column(name = "is_deal_premium")
    private short isDealPremium;

    @Column(name = "deal_charge")
    private int charge;

    @Column(name = "start_datetime")
    private Date startDatetime;

    @Column(name = "end_datetime")
    private Date endDatetime;

    @Column(name = "age_min")
    private Short ageMin;

    @Column(name = "age_max")
    private Short ageMax;

    @Column(name = "type_of_deal")
    private Short typeOfDeal;

    @Column(name = "deal_status")
    private Short dealStatus;

    @Column(name = "created_by")
    private String createdBy;

    @Column(name = "created_on")
    private Date createdOn;

    @Column(name = "updated_by")
    private String updatedBy;

    @Column(name = "updated_on")
    private Date updatedOn;

    @Column(name = "mcpm_id")
    private Long mcpmId;

    @Column(name = "deal_image")
    private String dealImage;

    @Column(name = "start_time")
    private Time startTime;

    @Column(name = "end_time")
    private Time endTime;

    @Column(name = "time_check")
    private Short timeCheck;

    @Column(name = "tnc")
    private String campaignTnC;


    @Column(name="coupon_fkey")
    private long couponId;

    @OneToMany(mappedBy = "merchantBranchDeals", cascade = CascadeType.ALL)
    private Set<MerchantBranchDetailsBranchDealsMapDo> merchantBranchDetailsBranchDealsMaps = new HashSet<MerchantBranchDetailsBranchDealsMapDo>(0);



    public long getMerchantDealsPkey() {
        return merchantDealsPkey;
    }

    public void setMerchantDealsPkey(long merchantDealsPkey) {
        this.merchantDealsPkey = merchantDealsPkey;
    }

    public String getTargetSex() {
        return targetSex;
    }

    public void setTargetSex(String targetSex) {
        this.targetSex = targetSex;
    }

    public Boolean getHasFixedCouponCode() {
        return hasFixedCouponCode;
    }

    public void setHasFixedCouponCode(Boolean hasFixedCouponCode) {
        this.hasFixedCouponCode = hasFixedCouponCode;
    }

    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public long getNoOfDeals() {
        return noOfDeals;
    }

    public void setNoOfDeals(long noOfDeals) {
        this.noOfDeals = noOfDeals;
    }

    public short getIsDealPremium() {
        return isDealPremium;
    }

    public void setIsDealPremium(short isDealPremium) {
        this.isDealPremium = isDealPremium;
    }

    public int getCharge() {
        return charge;
    }

    public void setCharge(int charge) {
        this.charge = charge;
    }

    public Date getStartDatetime() {
        return startDatetime;
    }

    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    public Date getEndDatetime() {
        return endDatetime;
    }

    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    public Short getAgeMin() {
        return ageMin;
    }

    public void setAgeMin(Short ageMin) {
        this.ageMin = ageMin;
    }

    public Short getAgeMax() {
        return ageMax;
    }

    public void setAgeMax(Short ageMax) {
        this.ageMax = ageMax;
    }

    public Short getTypeOfDeal() {
        return typeOfDeal;
    }

    public void setTypeOfDeal(Short typeOfDeal) {
        this.typeOfDeal = typeOfDeal;
    }

    public Short getDealStatus() {
        return dealStatus;
    }

    public void setDealStatus(Short dealStatus) {
        this.dealStatus = dealStatus;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Long getMcpmId() {
        return mcpmId;
    }

    public void setMcpmId(Long mcpmId) {
        this.mcpmId = mcpmId;
    }

    public String getDealImage() {
        return dealImage;
    }

    public void setDealImage(String dealImage) {
        this.dealImage = dealImage;
    }

    public Time getStartTime() {
        return startTime;
    }

    public void setStartTime(Time startTime) {
        this.startTime = startTime;
    }

    public Time getEndTime() {
        return endTime;
    }

    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }

    public Short getTimeCheck() {
        return timeCheck;
    }

    public void setTimeCheck(Short timeCheck) {
        this.timeCheck = timeCheck;
    }

    public String getCampaignTnC() {
        return campaignTnC;
    }

    public void setCampaignTnC(String campaignTnC) {
        this.campaignTnC = campaignTnC;
    }

    public Set<MerchantBranchDetailsBranchDealsMapDo> getMerchantBranchDetailsBranchDealsMaps() {
        return merchantBranchDetailsBranchDealsMaps;
    }

    public void setMerchantBranchDetailsBranchDealsMaps(Set<MerchantBranchDetailsBranchDealsMapDo> merchantBranchDetailsBranchDealsMaps) {
        this.merchantBranchDetailsBranchDealsMaps = merchantBranchDetailsBranchDealsMaps;
    }

    public long getCouponId() {
        return couponId;
    }

    public void setCouponId(long couponId) {
        this.couponId = couponId;
    }
}


